version: '3'

services:
  node:
    build:
      context: ./
    volumes:
      - ./:/app
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DATABASE_URL: mongodb://root:root@mongo
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"